/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/plant.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Plant(props) {
  const { nodes, materials } = useGLTF('./models/plant.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={13.69}>
        <group position={[0, 0.105, 0]}>
          <mesh geometry={nodes.Leaf_01_12.geometry} material={materials['Jade Leaves']} position={[0.102, 0.307, 0]} rotation={[1.061, -0.839, -3.01]} />
          <mesh geometry={nodes.Leaf_01_14.geometry} material={materials['Jade Leaves']} position={[0.081, 0.264, 0.023]} rotation={[1.032, -0.667, 1.794]} />
          <mesh geometry={nodes.Leaf_01_18.geometry} material={materials['Jade Leaves']} position={[0.073, 0.336, 0.076]} rotation={[1.232, -0.488, -1.552]} />
          <mesh geometry={nodes.Leaf_01_21.geometry} material={materials['Jade Leaves']} position={[0.012, 0.272, 0.001]} rotation={[0.761, -0.033, 0.372]} />
          <mesh geometry={nodes.Leaf_01_22.geometry} material={materials['Jade Leaves']} position={[0.002, 0.327, 0.004]} rotation={[2.558, 0.016, 0.309]} />
          <mesh geometry={nodes.Leaf_01_25.geometry} material={materials['Jade Leaves']} position={[0.048, 0.189, -0.062]} rotation={[1.148, -0.204, -0.154]} />
          <mesh geometry={nodes.Leaf_01_26.geometry} material={materials['Jade Leaves']} position={[0.071, 0.243, -0.078]} rotation={[1.68, -0.627, 0.185]} />
          <mesh geometry={nodes.Leaf_01_29.geometry} material={materials['Jade Leaves']} position={[0.08, 0.127, 0.004]} rotation={[1.659, -0.091, 1.126]} />
          <mesh geometry={nodes.Leaf_01_3.geometry} material={materials['Jade Leaves']} position={[-0.056, 0.184, 0.014]} rotation={[1, 0.64, -1.806]} />
          <mesh geometry={nodes.Leaf_01_34.geometry} material={materials['Jade Leaves']} position={[0.072, 0.121, 0.006]} rotation={[1.962, -1.013, -0.032]} />
          <mesh geometry={nodes.Leaf_01_36.geometry} material={materials['Jade Leaves']} position={[-0.024, 0.225, 0.004]} rotation={[1.473, 0.552, -1.396]} />
          <mesh geometry={nodes.Leaf_01_37.geometry} material={materials['Jade Leaves']} position={[0.016, 0.207, 0.008]} rotation={[1.306, 1.125, 0.085]} />
          <mesh geometry={nodes.Leaf_01_4.geometry} material={materials['Jade Leaves']} position={[-0.078, 0.229, -0.016]} rotation={[0.943, -0.84, -1.823]} />
          <mesh geometry={nodes.Leaf_01_42.geometry} material={materials['Jade Leaves']} position={[-0.007, 0.199, -0.091]} rotation={[1.02, 0.35, 2.413]} />
          <mesh geometry={nodes.Leaf_01_44.geometry} material={materials['Jade Leaves']} position={[0.022, 0.147, -0.048]} rotation={[0.566, 0.246, 0.895]} />
          <mesh geometry={nodes.Leaf_01_47.geometry} material={materials['Jade Leaves']} position={[0.02, 0.162, 0.023]} rotation={[1.797, -0.14, -2.822]} />
          <mesh geometry={nodes.Leaf_01_49.geometry} material={materials['Jade Leaves']} position={[0.02, 0.169, 0.027]} rotation={[2.94, -1.177, -0.552]} />
          <mesh geometry={nodes.Leaf_01_50.geometry} material={materials['Jade Leaves']} position={[-0.008, 0.053, 0.035]} rotation={[1.6, -0.137, -2.769]} />
          <mesh geometry={nodes.Leaf_01_52.geometry} material={materials['Jade Leaves']} position={[-0.008, 0.059, 0.039]} rotation={[2.565, -0.783, -1.01]} />
          <mesh geometry={nodes.Leaf_01_53.geometry} material={materials['Jade Leaves']} position={[0.072, 0.234, -0.014]} rotation={[1.832, -0.048, -0.312]} />
          <mesh geometry={nodes.Leaf_01_55.geometry} material={materials['Jade Leaves']} position={[0.072, 0.241, -0.015]} rotation={[1.601, 0.952, 1.08]} />
          <mesh geometry={nodes.Leaf_01_7.geometry} material={materials['Jade Leaves']} position={[-0.048, 0.177, 0.036]} rotation={[2.242, 0.921, -1.435]} />
          <mesh geometry={nodes.Leaf_01_8.geometry} material={materials['Jade Leaves']} position={[-0.042, 0.226, 0.071]} rotation={[1.643, -0.794, -1.675]} />
          <mesh geometry={nodes.Leaf_02_12.geometry} material={materials['Jade Leaves']} position={[0.093, 0.294, 0.006]} rotation={[0.862, -0.554, -3.025]} />
          <mesh geometry={nodes.Leaf_02_14.geometry} material={materials['Jade Leaves']} position={[0.097, 0.301, 0.002]} rotation={[1.572, -1.052, -1.014]} />
          <mesh geometry={nodes.Leaf_02_15.geometry} material={materials['Jade Leaves']} position={[0.106, 0.313, 0.001]} rotation={[1.772, -0.821, -0.931]} />
          <mesh geometry={nodes.Leaf_02_16.geometry} material={materials['Jade Leaves']} position={[0.075, 0.281, 0.053]} rotation={[1.583, 0.112, -0.143]} />
          <mesh geometry={nodes.Leaf_02_18.geometry} material={materials['Jade Leaves']} position={[0.076, 0.318, 0.07]} rotation={[1.99, -0.337, -1.739]} />
          <mesh geometry={nodes.Leaf_02_2.geometry} material={materials['Jade Leaves']} position={[-0.065, 0.198, 0.004]} rotation={[0.6, 0.443, -0.067]} />
          <mesh geometry={nodes.Leaf_02_21.geometry} material={materials['Jade Leaves']} position={[0.077, 0.268, 0.044]} rotation={[2.11, -0.199, 1.407]} />
          <mesh geometry={nodes.Leaf_02_22.geometry} material={materials['Jade Leaves']} position={[0.072, 0.294, 0.06]} rotation={[1.985, -0.301, 1.416]} />
          <mesh geometry={nodes.Leaf_02_24.geometry} material={materials['Jade Leaves']} position={[0.009, 0.289, 0.001]} rotation={[1.607, 0.027, 1.843]} />
          <mesh geometry={nodes.Leaf_02_28.geometry} material={materials['Jade Leaves']} position={[0.052, 0.206, -0.067]} rotation={[1.274, -0.88, 1.43]} />
          <mesh geometry={nodes.Leaf_02_37.geometry} material={materials['Jade Leaves']} position={[0.072, 0.121, 0.007]} rotation={[0.721, -0.433, 2.193]} />
          <mesh geometry={nodes.Leaf_02_40.geometry} material={materials['Jade Leaves']} position={[-0.024, 0.225, 0.004]} rotation={[1.283, 1.077, 1.888]} />
          <mesh geometry={nodes.Leaf_02_44.geometry} material={materials['Jade Leaves']} position={[-0.001, 0.173, -0.078]} rotation={[0.935, 0.3, 2.41]} />
          <mesh geometry={nodes.Leaf_02_46.geometry} material={materials['Jade Leaves']} position={[-0.006, 0.187, -0.087]} rotation={[0.967, -0.139, -2.359]} />
          <mesh geometry={nodes.Leaf_02_47.geometry} material={materials['Jade Leaves']} position={[-0.007, 0.209, -0.093]} rotation={[0.925, -0.553, -2.546]} />
          <mesh geometry={nodes.Leaf_02_48.geometry} material={materials['Jade Leaves']} position={[0.02, 0.163, 0.023]} rotation={[2.493, 0.106, 0.333]} />
          <mesh geometry={nodes.Leaf_02_49.geometry} material={materials['Jade Leaves']} position={[0.02, 0.156, 0.019]} rotation={[1.939, 0.541, -1.164]} />
          <mesh geometry={nodes.Leaf_02_51.geometry} material={materials['Jade Leaves']} position={[0.021, 0.156, 0.019]} rotation={[2.255, -0.264, 1.93]} />
          <mesh geometry={nodes.Leaf_02_52.geometry} material={materials['Jade Leaves']} position={[0.02, 0.169, 0.027]} rotation={[1.751, 0.534, 1.96]} />
          <mesh geometry={nodes.Leaf_02_53.geometry} material={materials['Jade Leaves']} position={[-0.007, 0.053, 0.035]} rotation={[2.792, 0.306, 0.255]} />
          <mesh geometry={nodes.Leaf_02_54.geometry} material={materials['Jade Leaves']} position={[-0.005, 0.049, 0.028]} rotation={[2.488, 0.844, -1.212]} />
          <mesh geometry={nodes.Leaf_02_56.geometry} material={materials['Jade Leaves']} position={[-0.004, 0.049, 0.028]} rotation={[2.788, -0.106, 1.808]} />
          <mesh geometry={nodes.Leaf_02_57.geometry} material={materials['Jade Leaves']} position={[-0.008, 0.059, 0.039]} rotation={[1.796, 0.703, 2.087]} />
          <mesh geometry={nodes.Leaf_02_58.geometry} material={materials['Jade Leaves']} position={[0.073, 0.234, -0.014]} rotation={[0.951, 0.215, 2.908]} />
          <mesh geometry={nodes.Leaf_02_59.geometry} material={materials['Jade Leaves']} position={[0.072, 0.228, -0.007]} rotation={[0.342, -0.833, 1.044]} />
          <mesh geometry={nodes.Leaf_02_6.geometry} material={materials['Jade Leaves']} position={[-0.049, 0.192, 0.049]} rotation={[2.391, -0.152, 0.195]} />
          <mesh geometry={nodes.Leaf_03_10.geometry} material={materials['Jade Leaves']} position={[-0.047, 0.202, 0.062]} rotation={[2.087, -0.347, 1.592]} />
          <mesh geometry={nodes.Leaf_03_13.geometry} material={materials['Jade Leaves']} position={[0.086, 0.277, 0.013]} rotation={[1.041, -0.54, 0.202]} />
          <mesh geometry={nodes.Leaf_03_15.geometry} material={materials['Jade Leaves']} position={[0.093, 0.293, 0.005]} rotation={[1.351, -0.448, 0.355]} />
          <mesh geometry={nodes.Leaf_03_16.geometry} material={materials['Jade Leaves']} position={[0.086, 0.278, 0.014]} rotation={[0.962, -0.552, -2.98]} />
          <mesh geometry={nodes.Leaf_03_18.geometry} material={materials['Jade Leaves']} position={[0.097, 0.301, 0.002]} rotation={[1.144, -0.246, 1.844]} />
          <mesh geometry={nodes.Leaf_03_2.geometry} material={materials['Jade Leaves']} position={[-0.077, 0.222, -0.01]} rotation={[0.479, 0.154, 3.007]} />
          <mesh geometry={nodes.Leaf_03_20.geometry} material={materials['Jade Leaves']} position={[0.075, 0.307, 0.067]} rotation={[1.76, -0.034, 2.971]} />
          <mesh geometry={nodes.Leaf_03_24.geometry} material={materials['Jade Leaves']} position={[0.072, 0.294, 0.06]} rotation={[2.012, -0.128, -1.72]} />
          <mesh geometry={nodes.Leaf_03_26.geometry} material={materials['Jade Leaves']} position={[0.076, 0.318, 0.07]} rotation={[2.129, 0.478, 1.392]} />
          <mesh geometry={nodes.Leaf_03_27.geometry} material={materials['Jade Leaves']} position={[0.002, 0.317, 0.001]} rotation={[1.923, -0.321, -1.301]} />
          <mesh geometry={nodes.Leaf_03_29.geometry} material={materials['Jade Leaves']} position={[0.012, 0.272, 0.003]} rotation={[2.359, 0.373, -3.121]} />
          <mesh geometry={nodes.Leaf_03_30.geometry} material={materials['Jade Leaves']} position={[0.003, 0.302, 0.001]} rotation={[1.601, 0.044, -2.87]} />
          <mesh geometry={nodes.Leaf_03_32.geometry} material={materials['Jade Leaves']} position={[0.067, 0.236, -0.073]} rotation={[0.874, -0.719, -1.86]} />
          <mesh geometry={nodes.Leaf_03_34.geometry} material={materials['Jade Leaves']} position={[0.048, 0.189, -0.061]} rotation={[2.081, -0.245, -3.073]} />
          <mesh geometry={nodes.Leaf_03_35.geometry} material={materials['Jade Leaves']} position={[0.062, 0.224, -0.071]} rotation={[1.334, -0.392, 3.042]} />
          <mesh geometry={nodes.Leaf_03_37.geometry} material={materials['Jade Leaves']} position={[0.044, 0.098, 0.006]} rotation={[1.621, -1.023, 1.238]} />
          <mesh geometry={nodes.Leaf_03_38.geometry} material={materials['Jade Leaves']} position={[0.062, 0.113, 0.007]} rotation={[1.276, -1.118, -2.187]} />
          <mesh geometry={nodes.Leaf_03_4.geometry} material={materials['Jade Leaves']} position={[-0.055, 0.184, 0.014]} rotation={[0.812, -0.235, 1.377]} />
          <mesh geometry={nodes.Leaf_03_40.geometry} material={materials['Jade Leaves']} position={[0.055, 0.106, 0.007]} rotation={[1.467, -0.855, 2.692]} />
          <mesh geometry={nodes.Leaf_03_43.geometry} material={materials['Jade Leaves']} position={[-0.04, 0.241, 0.003]} rotation={[1.209, 0.968, 1.867]} />
          <mesh geometry={nodes.Leaf_03_47.geometry} material={materials['Jade Leaves']} position={[0.016, 0.207, 0.009]} rotation={[2.432, 0.823, 2.255]} />
          <mesh geometry={nodes.Leaf_03_48.geometry} material={materials['Jade Leaves']} position={[-0.013, 0.219, 0.01]} rotation={[0.706, 0.898, -2.4]} />
          <mesh geometry={nodes.Leaf_03_5.geometry} material={materials['Jade Leaves']} position={[-0.072, 0.212, -0.005]} rotation={[1.128, 0.421, 1.292]} />
          <mesh geometry={nodes.Leaf_03_51.geometry} material={materials['Jade Leaves']} position={[0.012, 0.159, -0.058]} rotation={[0.314, 0.782, -0.451]} />
          <mesh geometry={nodes.Leaf_03_53.geometry} material={materials['Jade Leaves']} position={[-0.002, 0.172, -0.079]} rotation={[1.086, 0.164, -0.766]} />
          <mesh geometry={nodes.Leaf_03_54.geometry} material={materials['Jade Leaves']} position={[0.012, 0.16, -0.058]} rotation={[0.736, 0.559, 2.424]} />
          <mesh geometry={nodes.Leaf_03_56.geometry} material={materials['Jade Leaves']} position={[-0.005, 0.186, -0.087]} rotation={[1.51, 0.379, 0.713]} />
          <mesh geometry={nodes.Leaf_03_68.geometry} material={materials['Jade Leaves']} position={[0.072, 0.228, -0.007]} rotation={[1.063, 0.711, -2.034]} />
          <mesh geometry={nodes.Leaf_03_69.geometry} material={materials['Jade Leaves']} position={[0.072, 0.241, -0.015]} rotation={[1.026, -0.523, -1.892]} />
          <mesh geometry={nodes.Leaf_03_7.geometry} material={materials['Jade Leaves']} position={[-0.043, 0.215, 0.069]} rotation={[1.396, -0.053, 3.047]} />
          <mesh geometry={nodes.Leaf_03_9.geometry} material={materials['Jade Leaves']} position={[-0.046, 0.177, 0.036]} rotation={[2.417, -0.673, 1.676]} />
          <mesh geometry={nodes.Leaf_04_11.geometry} material={materials['Jade Leaves']} position={[-0.039, 0.235, 0.072]} rotation={[0.927, -0.003, 2.988]} />
          <mesh geometry={nodes.Leaf_04_14.geometry} material={materials['Jade Leaves']} position={[-0.039, 0.235, 0.072]} rotation={[2.041, -0.139, -0.065]} />
          <mesh geometry={nodes.Leaf_04_15.geometry} material={materials['Jade Leaves']} position={[-0.042, 0.226, 0.071]} rotation={[1.732, 0.194, 1.496]} />
          <mesh geometry={nodes.Leaf_04_19.geometry} material={materials['Jade Leaves']} position={[0.08, 0.265, 0.023]} rotation={[0.892, 0.003, -1.396]} />
          <mesh geometry={nodes.Leaf_04_2.geometry} material={materials['Jade Leaves']} position={[-0.065, 0.198, 0.005]} rotation={[0.827, 0.563, 2.903]} />
          <mesh geometry={nodes.Leaf_04_21.geometry} material={materials['Jade Leaves']} position={[0.09, 0.285, 0.01]} rotation={[1.061, -0.242, -1.347]} />
          <mesh geometry={nodes.Leaf_04_23.geometry} material={materials['Jade Leaves']} position={[0.075, 0.281, 0.054]} rotation={[2.38, 0.122, 2.943]} />
          <mesh geometry={nodes.Leaf_04_25.geometry} material={materials['Jade Leaves']} position={[0.075, 0.329, 0.076]} rotation={[0.923, 0.344, -3]} />
          <mesh geometry={nodes.Leaf_04_28.geometry} material={materials['Jade Leaves']} position={[0.075, 0.329, 0.076]} rotation={[2.091, 0.273, -0.255]} />
          <mesh geometry={nodes.Leaf_04_29.geometry} material={materials['Jade Leaves']} position={[0.076, 0.267, 0.045]} rotation={[2.282, 0.707, -1.783]} />
          <mesh geometry={nodes.Leaf_04_30.geometry} material={materials['Jade Leaves']} position={[0.073, 0.336, 0.076]} rotation={[1.21, 0.661, 1.592]} />
          <mesh geometry={nodes.Leaf_04_31.geometry} material={materials['Jade Leaves']} position={[0.008, 0.288, 0.001]} rotation={[1.389, 0.676, -1.219]} />
          <mesh geometry={nodes.Leaf_04_33.geometry} material={materials['Jade Leaves']} position={[0.002, 0.33, 0.005]} rotation={[2.331, -0.631, -1.215]} />
          <mesh geometry={nodes.Leaf_04_36.geometry} material={materials['Jade Leaves']} position={[0.002, 0.33, 0.005]} rotation={[1.97, 0.461, 1.89]} />
          <mesh geometry={nodes.Leaf_04_37.geometry} material={materials['Jade Leaves']} position={[0.001, 0.327, 0.004]} rotation={[1.467, -0.269, -2.987]} />
          <mesh geometry={nodes.Leaf_04_38.geometry} material={materials['Jade Leaves']} position={[0.052, 0.207, -0.067]} rotation={[1.365, -0.194, -1.662]} />
          <mesh geometry={nodes.Leaf_04_4.geometry} material={materials['Jade Leaves']} position={[-0.074, 0.238, -0.021]} rotation={[0.636, -0.193, 2.863]} />
          <mesh geometry={nodes.Leaf_04_40.geometry} material={materials['Jade Leaves']} position={[0.076, 0.25, -0.082]} rotation={[0.945, -1.027, -1.853]} />
          <mesh geometry={nodes.Leaf_04_43.geometry} material={materials['Jade Leaves']} position={[0.076, 0.25, -0.082]} rotation={[1.201, 0.086, 1.426]} />
          <mesh geometry={nodes.Leaf_04_44.geometry} material={materials['Jade Leaves']} position={[0.071, 0.243, -0.078]} rotation={[0.464, -0.438, 2.645]} />
          <mesh geometry={nodes.Leaf_04_45.geometry} material={materials['Jade Leaves']} position={[0.044, 0.098, 0.006]} rotation={[1.715, -0.838, -1.828]} />
          <mesh geometry={nodes.Leaf_04_46.geometry} material={materials['Jade Leaves']} position={[0.079, 0.127, 0.004]} rotation={[0.798, -1.028, -2.548]} />
          <mesh geometry={nodes.Leaf_04_48.geometry} material={materials['Jade Leaves']} position={[0.027, 0.094, 0.004]} rotation={[2.935, -1.126, -2.273]} />
          <mesh geometry={nodes.Leaf_04_56.geometry} material={materials['Jade Leaves']} position={[-0.034, 0.234, 0.003]} rotation={[2.297, 0.647, -0.37]} />
          <mesh geometry={nodes.Leaf_04_58.geometry} material={materials['Jade Leaves']} position={[-0.034, 0.234, 0.003]} rotation={[1.02, 0.6, -2.693]} />
          <mesh geometry={nodes.Leaf_04_62.geometry} material={materials['Jade Leaves']} position={[0.021, 0.148, -0.047]} rotation={[1.252, 0.79, -2.61]} />
          <mesh geometry={nodes.Leaf_04_64.geometry} material={materials['Jade Leaves']} position={[0.003, 0.165, -0.067]} rotation={[0.639, 0.393, -2.232]} />
          <mesh geometry={nodes.Leaf_04_7.geometry} material={materials['Jade Leaves']} position={[-0.074, 0.238, -0.022]} rotation={[1.794, -0.333, 0.059]} />
          <mesh geometry={nodes.Leaf_04_8.geometry} material={materials['Jade Leaves']} position={[-0.078, 0.229, -0.016]} rotation={[1.151, 0.113, 1.403]} />
          <mesh geometry={nodes.Leaf_04_9.geometry} material={materials['Jade Leaves']} position={[-0.049, 0.191, 0.05]} rotation={[2.788, -0.082, -3.026]} />
          <mesh geometry={nodes.Leaf_05_18.geometry} material={materials['Jade Leaves']} position={[-0.043, 0.215, 0.069]} rotation={[2.271, -0.088, 0.063]} />
          <mesh geometry={nodes.Leaf_05_21.geometry} material={materials['Jade Leaves']} position={[-0.048, 0.202, 0.062]} rotation={[2.085, -0.266, -1.55]} />
          <mesh geometry={nodes.Leaf_05_26.geometry} material={materials['Jade Leaves']} position={[0.102, 0.307, 0]} rotation={[2.202, -0.277, 0.811]} />
          <mesh geometry={nodes.Leaf_05_29.geometry} material={materials['Jade Leaves']} position={[0.091, 0.285, 0.011]} rotation={[1.048, -0.185, 1.792]} />
          <mesh geometry={nodes.Leaf_05_31.geometry} material={materials['Jade Leaves']} position={[0.106, 0.313, 0.001]} rotation={[1.183, 0.2, 1.999]} />
          <mesh geometry={nodes.Leaf_05_39.geometry} material={materials['Jade Leaves']} position={[0.075, 0.307, 0.066]} rotation={[2.117, -0.092, -0.148]} />
          <mesh geometry={nodes.Leaf_05_48.geometry} material={materials['Jade Leaves']} position={[0.003, 0.317, 0.001]} rotation={[1.69, 0.508, 1.865]} />
          <mesh geometry={nodes.Leaf_05_51.geometry} material={materials['Jade Leaves']} position={[0.003, 0.302, 0]} rotation={[1.64, 0.054, 0.27]} />
          <mesh geometry={nodes.Leaf_05_6.geometry} material={materials['Jade Leaves']} position={[-0.077, 0.222, -0.01]} rotation={[1.101, 0.046, -0.199]} />
          <mesh geometry={nodes.Leaf_05_60.geometry} material={materials['Jade Leaves']} position={[0.068, 0.236, -0.073]} rotation={[1.069, 0.005, 1.355]} />
          <mesh geometry={nodes.Leaf_05_63.geometry} material={materials['Jade Leaves']} position={[0.062, 0.224, -0.072]} rotation={[1.639, -0.404, 0.02]} />
          <mesh geometry={nodes.Leaf_05_69.geometry} material={materials['Jade Leaves']} position={[0.063, 0.112, 0.007]} rotation={[1.66, -0.606, 1.258]} />
          <mesh geometry={nodes.Leaf_05_72.geometry} material={materials['Jade Leaves']} position={[0.027, 0.094, 0.003]} rotation={[1.196, -1.17, -0.779]} />
          <mesh geometry={nodes.Leaf_05_73.geometry} material={materials['Jade Leaves']} position={[0.055, 0.106, 0.006]} rotation={[1.735, -0.917, -0.241]} />
          <mesh geometry={nodes.Leaf_05_75.geometry} material={materials['Jade Leaves']} position={[-0.006, 0.218, 0.014]} rotation={[0.144, 1.131, -0.339]} />
          <mesh geometry={nodes.Leaf_05_76.geometry} material={materials['Jade Leaves']} position={[-0.04, 0.241, 0.003]} rotation={[1.477, -0.136, -1.403]} />
          <mesh geometry={nodes.Leaf_05_78.geometry} material={materials['Jade Leaves']} position={[-0.005, 0.218, 0.014]} rotation={[0.357, 1.087, 2.612]} />
          <mesh geometry={nodes.Leaf_05_80.geometry} material={materials['Jade Leaves']} position={[-0.013, 0.219, 0.01]} rotation={[0.841, 0.964, 0.633]} />
          <mesh geometry={nodes.Leaf_05_83.geometry} material={materials['Jade Leaves']} position={[-0.007, 0.199, -0.092]} rotation={[1.803, -0.391, -0.711]} />
          <mesh geometry={nodes.Leaf_05_86.geometry} material={materials['Jade Leaves']} position={[0.004, 0.165, -0.068]} rotation={[0.564, 0.301, 0.934]} />
          <mesh geometry={nodes.Leaf_05_88.geometry} material={materials['Jade Leaves']} position={[-0.007, 0.209, -0.093]} rotation={[1.808, 0.221, 0.764]} />
          <mesh geometry={nodes.Leaf_05_9.geometry} material={materials['Jade Leaves']} position={[-0.072, 0.212, -0.005]} rotation={[1.073, 0.232, -1.832]} />
        </group>
        <group position={[0.022, 0.338, 0.001]}>
          <mesh geometry={nodes.Small_Leaf_0.geometry} material={materials['Jade Leaves']} position={[-0.061, 0.008, 0.07]} rotation={[-1.898, 0.379, -2.449]} />
          <mesh geometry={nodes.Small_Leaf_1.geometry} material={materials['Jade Leaves']} position={[-0.061, 0.008, 0.07]} rotation={[-1.333, -0.342, -2.46]} />
          <mesh geometry={nodes.Small_Leaf_10.geometry} material={materials['Jade Leaves']} position={[0.056, 0.02, -0.085]} rotation={[-1.611, 0.444, 1.4]} />
          <mesh geometry={nodes.Small_Leaf_11.geometry} material={materials['Jade Leaves']} position={[0.056, 0.02, -0.085]} rotation={[-2.612, 0.395, 1.839]} />
          <mesh geometry={nodes.Small_Leaf_12.geometry} material={materials['Jade Leaves']} position={[0.059, -0.103, 0.002]} rotation={[-1.317, 0.714, 1.739]} />
          <mesh geometry={nodes.Small_Leaf_13.geometry} material={materials['Jade Leaves']} position={[0.059, -0.103, 0.002]} rotation={[-2.271, 0.308, 2.244]} />
          <mesh geometry={nodes.Small_Leaf_14.geometry} material={materials['Jade Leaves']} position={[-0.066, 0.015, 0.001]} rotation={[-1.397, -0.491, 1.495]} />
          <mesh geometry={nodes.Small_Leaf_15.geometry} material={materials['Jade Leaves']} position={[-0.065, 0.015, 0.001]} rotation={[-2.34, -0.239, 1.132]} />
          <mesh geometry={nodes.Small_Leaf_16.geometry} material={materials['Jade Leaves']} position={[-0.028, -0.019, -0.095]} rotation={[-1.982, 0.483, -2.452]} />
          <mesh geometry={nodes.Small_Leaf_17.geometry} material={materials['Jade Leaves']} position={[-0.028, -0.019, -0.095]} rotation={[-1.437, -0.256, -2.52]} />
          <mesh geometry={nodes.Small_Leaf_18.geometry} material={materials['Jade Leaves']} position={[0, -0.058, 0.029]} rotation={[-0.79, 0.094, 0.716]} />
          <mesh geometry={nodes.Small_Leaf_19.geometry} material={materials['Jade Leaves']} position={[0, -0.059, 0.029]} rotation={[-1.539, 0.708, 1.035]} />
          <mesh geometry={nodes.Small_Leaf_2.geometry} material={materials['Jade Leaves']} position={[-0.094, 0.011, -0.025]} rotation={[-2.066, 0.668, -2.801]} />
          <mesh geometry={nodes.Small_Leaf_20.geometry} material={materials['Jade Leaves']} position={[-0.03, -0.172, 0.04]} rotation={[-0.594, 0.008, 1.39]} />
          <mesh geometry={nodes.Small_Leaf_21.geometry} material={materials['Jade Leaves']} position={[-0.03, -0.172, 0.04]} rotation={[-1.496, 0.147, 1.466]} />
          <mesh geometry={nodes.Small_Leaf_22.geometry} material={materials['Jade Leaves']} position={[0.049, 0.012, -0.017]} rotation={[-2.254, -0.349, -1.284]} />
          <mesh geometry={nodes.Small_Leaf_23.geometry} material={materials['Jade Leaves']} position={[0.049, 0.012, -0.017]} rotation={[-1.397, -0.001, -1.123]} />
          <mesh geometry={nodes.Small_Leaf_3.geometry} material={materials['Jade Leaves']} position={[-0.094, 0.011, -0.025]} rotation={[-1.793, -0.204, -2.87]} />
          <mesh geometry={nodes.Small_Leaf_4.geometry} material={materials['Jade Leaves']} position={[0.085, 0.082, 0]} rotation={[-2.104, 0.432, -1.792]} />
          <mesh geometry={nodes.Small_Leaf_5.geometry} material={materials['Jade Leaves']} position={[0.085, 0.082, 0]} rotation={[-1.22, 0.101, -2.043]} />
          <mesh geometry={nodes.Small_Leaf_6.geometry} material={materials['Jade Leaves']} position={[0.05, 0.105, 0.074]} rotation={[-1.573, -0.24, 1.182]} />
          <mesh geometry={nodes.Small_Leaf_7.geometry} material={materials['Jade Leaves']} position={[0.05, 0.105, 0.074]} rotation={[-2.402, 0.145, 1.139]} />
          <mesh geometry={nodes.Small_Leaf_8.geometry} material={materials['Jade Leaves']} position={[-0.02, 0.099, 0.005]} rotation={[-0.638, -0.008, 1.311]} />
          <mesh geometry={nodes.Small_Leaf_9.geometry} material={materials['Jade Leaves']} position={[-0.02, 0.099, 0.005]} rotation={[-1.529, 0.199, 1.402]} />
        </group>
        <group position={[0, 0.105, 0]}>
          <mesh geometry={nodes.Little_Soil_Peable_01.geometry} material={materials.Soil} position={[-0.054, 0.01, 0.021]} rotation={[-0.022, 0.001, 0.008]} />
          <mesh geometry={nodes.Little_Soil_Peable_01001.geometry} material={materials.Soil} position={[0.001, 0.011, 0.057]} rotation={[-0.016, -0.003, 0.02]} />
          <mesh geometry={nodes.Little_Soil_Peable_01002.geometry} material={materials.Soil} position={[0.061, 0.011, -0.003]} rotation={[-0.006, 0.001, 0.004]} />
          <mesh geometry={nodes.Little_Soil_Peable_01003.geometry} material={materials.Soil} position={[-0.049, 0.01, 0.002]} rotation={[0.027, -0.001, -0.043]} />
          <mesh geometry={nodes.Little_Soil_Peable_01004.geometry} material={materials.Soil} position={[0.048, 0.011, -0.021]} rotation={[-0.016, 0.008, -0.045]} />
          <mesh geometry={nodes.Little_Soil_Peable_01005.geometry} material={materials.Soil} position={[0.044, 0.011, -0.044]} rotation={[-0.012, 0.011, -0.091]} />
          <mesh geometry={nodes.Little_Soil_Peable_02.geometry} material={materials.Soil} position={[-0.02, 0.01, -0.031]} rotation={[-0.001, 0, 0.045]} />
          <mesh geometry={nodes.Little_Soil_Peable_02001.geometry} material={materials.Soil} position={[0.003, 0.011, 0.018]} rotation={[0.239, 0.008, 0.022]} />
          <mesh geometry={nodes.Little_Soil_Peable_02002.geometry} material={materials.Soil} position={[-0.035, 0.01, -0.05]} rotation={[-0.012, -0.001, -0.005]} />
          <mesh geometry={nodes.Little_Soil_Peable_02003.geometry} material={materials.Soil} position={[-0.045, 0.009, 0.009]} rotation={[-0.001, -0.001, -0.071]} />
          <mesh geometry={nodes.Little_Soil_Peable_02004.geometry} material={materials.Soil} position={[0.025, 0.01, -0.027]} rotation={[0.074, 0.001, 0.017]} />
          <mesh geometry={nodes.Little_Soil_Peable_02005.geometry} material={materials.Soil} position={[0.05, 0.011, -0.037]} rotation={[0.081, 0.002, 0.025]} />
          <mesh geometry={nodes.Little_Soil_Peable_02006.geometry} material={materials.Soil} position={[0.044, 0.011, -0.037]} rotation={[-0.004, 0.004, -0.087]} />
          <mesh geometry={nodes.Wood_Stick_01.geometry} material={materials['Wood Stick 01']} position={[-0.047, 0.01, 0.024]} rotation={[-0.085, 0.002, -0.051]} />
          <mesh geometry={nodes.Wood_Stick_01001.geometry} material={materials['Wood Stick 01']} position={[0.01, 0.011, 0.018]} rotation={[2.98, -0.192, -2.822]} />
          <mesh geometry={nodes.Wood_Stick_01002.geometry} material={materials['Wood Stick 01']} position={[0.054, 0.011, 0.014]} rotation={[0.05, 0.824, 0.829]} />
          <mesh geometry={nodes.Wood_Stick_01003.geometry} material={materials['Wood Stick 01']} position={[-0.029, 0.01, -0.048]} rotation={[0.001, -0.9, 0.004]} />
          <mesh geometry={nodes.Wood_Stick_02.geometry} material={materials['Wood Stick 02']} position={[0.031, 0.01, -0.025]} rotation={[0.126, 0.002, 0.069]} />
          <mesh geometry={nodes.Wood_Stick_02001.geometry} material={materials['Wood Stick 02']} position={[-0.015, 0.01, -0.036]} rotation={[2.876, -1.167, 2.882]} />
          <mesh geometry={nodes.Wood_Stick_02002.geometry} material={materials['Wood Stick 02']} position={[-0.018, 0.012, 0.011]} rotation={[2.848, -1.141, 2.694]} />
          <mesh geometry={nodes.Wood_Stick_02003.geometry} material={materials['Wood Stick 02']} position={[-0.015, 0.011, 0.055]} rotation={[2.596, 1.546, -2.594]} />
          <mesh geometry={nodes.Wood_Stick_03.geometry} material={materials['Wood Stick 03']} position={[0.05, 0.011, -0.014]} rotation={[0.053, 0.007, 0.073]} />
          <mesh geometry={nodes.Wood_Stick_03001.geometry} material={materials['Wood Stick 03']} position={[-0.039, 0.009, 0.006]} rotation={[0.043, -0.505, 0.058]} />
          <mesh geometry={nodes.Wood_Stick_03002.geometry} material={materials['Wood Stick 03']} position={[0.053, 0.011, -0.006]} rotation={[-0.11, 0.972, 0.146]} />
          <mesh geometry={nodes.Wood_Stick_03003.geometry} material={materials['Wood Stick 03']} position={[0.008, 0.011, 0.053]} rotation={[-0.15, -0.006, 0.062]} />
        </group>
        <mesh geometry={nodes.Pot_15_cm.geometry} material={materials['Terracotta pot 15 used']} />
        <mesh geometry={nodes.SOIL.geometry} material={materials.Soil} position={[0, 0.113, 0]} />
        <mesh geometry={nodes.Trunk.geometry} material={materials['Jade Trunk']} position={[0, 0.107, 0]}>
          <mesh geometry={nodes.Branch_0.geometry} material={materials['Jade Trunk']} position={[0.073, 0.216, 0.014]} rotation={[0.783, 0.334, 2.689]} />
          <mesh geometry={nodes.Branch_1.geometry} material={materials['Jade Trunk']} position={[0.001, 0.036, 0.011]} rotation={[2.362, -0.025, -0.329]} />
          <mesh geometry={nodes.Branch_2.geometry} material={materials['Jade Trunk']} position={[0.025, 0.138, 0.005]} rotation={[2.362, -0.025, 0.284]} />
          <mesh geometry={nodes.Branch_3.geometry} material={materials['Jade Trunk']} position={[0.03, 0.139, -0.04]} rotation={[0.567, 0.297, -0.33]} />
          <mesh geometry={nodes.Branch_4.geometry} material={materials['Jade Trunk']} position={[0.032, 0.203, 0.006]} rotation={[1.19, 1.079, -0.711]} />
          <mesh geometry={nodes.Branch_5.geometry} material={materials['Jade Trunk']} position={[0.012, 0.091, 0.003]} rotation={[1.582, -1.07, 2.871]} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('./models/plant.glb')
